# Transfer Entropy

## Introduction

## Nonlinear G-Causality {#nonlinearG}

To compute the nonlinear G-Causality, we use the concept of Transfer Entropy. Since its introduction [@PhysRevLett.85.461], Transfer Entropy has been recognized as an important tool in the analysis of causal relationships in nonlinear systems [@citeulike:1447442].
It detects directional and dynamical information [@10.1371/journal.pone.0109462] while not assuming any particular functional form to describe interactions among systems.


The Transfer Entropy can be defined as the difference between the conditional entropies: 
\begin{equation}
 TE\left(X \rightarrow Y\right \vert Z) =  H\left(Y^F\middle\vert Y^P,Z^P\right) - H\left(Y^F\middle\vert X^P, Y^P,Z^P\right),
(\#eq:TE)
\end{equation}
which can be rewritten as a sum of Shannon entropies:
\begin{align}
TE\left(X \rightarrow Y\right) = H\left(Y^P, X^P\right) - H\left(Y^F, Y^P, X^P\right) + H\left(Y^F, Y^P\right) - H\left(Y^P\right),
\end{align}

where $Y^F$ is a forward time-shifted version of $Y$ at lag $\Delta t$ relatively to the past time-series $X^P$,  $Y^P$ and $Z^P$.
Within this framework we say that $X$ does not G-cause $Y$ relative to side information $Z$ if and only if 
$H\left(Y^F\middle\vert Y^P,Z^P \right) = H\left(Y^F\middle\vert X^P, Y^P,Z^P\right)$, i.e., when $TE\left(X \rightarrow Y,Z^P\right) = 0$.

Empirically, we reject this null hypothesis of causality if the Transfer Entropy from $X$ to $Y$ is significantly higher than the shuffled version of the original data.

For this we estimate 400 replicates of $TE(X_{Shuffled} \rightarrow Y)$, where $X_{Shuffled}$ is a random permutation of $X$ relatively to $Y$.
We compute the randomized Transfer Entropy at each permutation for each time-shift ($\Delta t$) from 1 to 10 days. 
We then calculated the frequency at which the observed Transfer Entropy was equal or more extreme 
than the randomized Transfer Entropy. The statistical significance was assessed using p-value $< 0.05$ after Bonferroni correction.

## The Link Between Linear Granger-causality and Transfer Entropy

It has been shown [@PhysRevLett.103.238701] that linear G-causality and Transfer Entropy are equivalent 
if all processes are jointly Gaussian.
In particular, by assuming the standard measure ($l2$-norm loss function) of linear G-causality for the bivariate case as follows (see Section \@ref(LinearG) for more details on linear-Granger causality):

\begin{equation}
GC_{X \rightarrow Y} = \log\left( \frac{var(\epsilon_t)}{var( \widehat{\epsilon}_t)} \right),
(\#eq:GCGC)
\end{equation}

the following can be proved [@PhysRevLett.103.238701]:

\begin{align}
TE_{X \rightarrow Y} = GC_{X \rightarrow Y}/2.
(\#eq:GCGC2)
\end{align}

This result provides a direct mapping between the Transfer Entropy and the linear G-causality implemented in the standard VAR framework.
Hence, it is possible to estimate the TE both in its general form and with its equivalent form for linear G-causality. 

## Net Information Flow

Transfer-entropy is an asymmetric measure, i.e., $T_{X \rightarrow Y} \neq T_{Y \rightarrow X}$, and it thus allows 
the quantification of the directional coupling between systems. 
The Net Information Flow is defined as 
\begin{equation}
\widehat{TE}_{X \rightarrow Y} = TE_{X \rightarrow Y} - TE_{Y \rightarrow X}\;.
\end{equation}
One can interpret this quantity as a measure of the dominant direction of the information flow. In other words, 
a positive result indicates a dominant information flow from $X$ to $Y$ compared to the other direction
or, similarly, it indicates which system provides more predictive information about the other system [@Michalowicz:2013:HDE:2601840].

In the next sections we will provide empirical examples that show that Transfer Entropy can capture information flow in both linear and nonlinear systems.

## Empirical Experiment: Information Flow on Simulated Systems

In this section, we construct simulated systems and test the nonlinear and linear formulations of the net information flow. We show that only the nonlinear formulation of net information flow is able to capture the nonlinear relationships in the simulated systems.

For the nonlinear case, we compute Transfer Entropy as defined in Eq. \@ref(eq:TE).
Conversely, to estimate the linear version of the Net Information Flow, we computed the Transfer Entropy using Eq. \@ref(eq:GCGC2), i.e., 
by estimating linear G-causality Eq. \@ref(eq:GCGC) under a linear-VAR framework.



## Empirical Experiment: Information Flow on Global Markets
